### ISSUE TITLE
Cards with the same name but different code aren't available in the deck editor

### ISSUE THREAD

**Issue by olegshtch** [longagofaraway/Cockatrice#1]
<b>System Information:</b>
  
Client Version: 2.7.4-custom(d666186) (2020-07-19)
  
_______________________________________________________________________________________

  
Cards with repeated name like "Black Rock Shooter" `PD/S22-106` and "Hatsune Miku "Heartbeat"" `PD/S22-104a` are missed in the deck editor. I checked `cards.xml` and found them here.
The deck editor uses `CardInfoPerSetMap` structure which is map over names not codes.

**Comment by longagofaraway** [comment]
Nice find! Steps to reproduce:
1. Have all your sets disabled
2. Enable the needed sets

If your restart a game after the needed sets are enabled, cards with the same name will be displayed. But right now I don't see where the problem is. `CardInfoPerSetMap` uses short set names as keys, and they are keys for sets, like "WSPDTD" or "WSBLACK"

**Comment by longagofaraway** [comment]
fixed in 3812d58. Thanks for the issue!
